samples:
    Lens_lamottei: fastq_files/Lens_lamottei
    Lens_tomentosus: fastq_files/Lens_tomentosus
GenomeIndex: /Users/yasinkaymaz/Documents/data/Hg38/forGatk/GRCh38_idx
GenomeFa: /Users/yasinkaymaz/Documents/ChlP_GS/Nurbanu/CladePhylo/AGORA/Lc_agora/NC_027152.1.Lens_culinaris.fasta
RepeatRegions: /Users/yasinkaymaz/Documents/MedGenetics/BioinfoAnalysis/target_regions_chr.bed
